version: "3.7"
services:
  app:
    build:
      args:
        user: dario
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: zhental
    container_name: zhental-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - zhental

  db:
    image: mysql:8.0
    container_name: zhental-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'zhental'
      MYSQL_ROOT_PASSWORD: 'test123'
      MYSQL_PASSWORD: 'test123'
      MYSQL_USER: 'root'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - zhental-datavolume:/var/lib/mysql
    networks:
      - zhental

  nginx:
    image: nginx:alpine
    container_name: zhental-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - zhental

volumes:
  zhental-datavolume:

networks:
  zhental:
    driver: bridge
